### ISSUE TITLE
Changes in test_region_titles.py

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/rosstat-806-regional#6]
- [x] `test_region_titles.py` must be in same folder as `funcs.py`
- [x] constants needed for testing must be importable from `test` folder, which shoudl be a package (with `__init__.py`). Use of path change `sys.path.append(os.path.dirname(os.path.dirname(__file__)))` is avoided this way.
- [x] `test` folder and package better be renames, because `test` usually holds tests
- [x] after above is done change section below `__name__=="__main__":` in `func.py`

**Comment by Alexander-Safr** [comment]
ok

**Comment by epogrebnyak** [comment]
Closed by 9a98de0f9e03b611910239b2ff5871f3b2f27a18
