### ISSUE TITLE
'reference_region_names.py'  (renamed file  + 2 comments inside)

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/rosstat-806-regional#7]
- [x] renamed this file from - need adjust imports in code 
- [x] see two comments inside code:
  - https://github.com/epogrebnyak/rosstat-806-regional/blob/master/reference_region_names.py#L44 
  - https://github.com/epogrebnyak/rosstat-806-regional/blob/master/reference_region_names.py#L98 

If reference name changes  above produce too much code changes in do not do them now.

**Comment by Alexander-Safr** [comment]
ok

**Comment by epogrebnyak** [comment]
Closed by 9a98de0f9e03b611910239b2ff5871f3b2f27a18
